// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSpZaKwy6LfabCZE1IbG3i7SNEgErz1Ik',
    appId: '1:825265177541:web:16e4ae7b72e9c1c45d01ac',
    messagingSenderId: '825265177541',
    projectId: 'bloc-ecommerce-180824',
    authDomain: 'bloc-ecommerce-180824.firebaseapp.com',
    storageBucket: 'bloc-ecommerce-180824.appspot.com',
    measurementId: 'G-RQ07R7KRVP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvi6Oh2yxeRsAuq0rZ8bds9WAhujtXyA0',
    appId: '1:825265177541:android:381d03504d1646945d01ac',
    messagingSenderId: '825265177541',
    projectId: 'bloc-ecommerce-180824',
    storageBucket: 'bloc-ecommerce-180824.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDURR0bhuPEWThpTZIdaSeF7CTiNQMQ6Y8',
    appId: '1:825265177541:ios:042e7fd843df6b595d01ac',
    messagingSenderId: '825265177541',
    projectId: 'bloc-ecommerce-180824',
    storageBucket: 'bloc-ecommerce-180824.appspot.com',
    iosBundleId: 'com.example.blocCleanArchitectureEcommerce180824',
  );

}